# Generated by Django 5.0.6 on 2024-08-08 17:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vital',
            name='id',
        ),
        migrations.AlterField(
            model_name='information',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='informations', serialize=False, to='health_app.patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='cause',
            field=models.TextField(default='Visit was not established yet '),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 8, 20, 37, 16, 463093)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='management',
            field=models.TextField(default='Visit was not established yet'),
        ),
        migrations.AlterField(
            model_name='vital',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vitals', serialize=False, to='health_app.visit'),
        ),
    ]
